# Generated by Django 4.1.3 on 2022-12-19 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0002_alter_clase_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reserva', to=settings.AUTH_USER_MODEL),
        ),
    ]
