# Generated by Django 4.1.3 on 2022-12-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reservas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='reservado',
            field=models.BooleanField(default=True, verbose_name='Reservado'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='reservado',
            field=models.BooleanField(default=True, verbose_name='Reservado'),
        ),
        migrations.AddField(
            model_name='material',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Reservado'),
        ),
    ]
