# Generated by Django 4.1.3 on 2022-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_clase_reservado_equipo_reservado_material_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='reservado',
            new_name='disponible',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='reservado',
            new_name='disponible',
        ),
    ]
