# Generated by Django 4.1.3 on 2022-12-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_rename_reservado_clase_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='material',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
