# Generated by Django 4.1.3 on 2022-12-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_clase_disponible_alter_equipo_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imagen',
            field=models.ImageField(null=True, upload_to='material'),
        ),
    ]
