# Generated by Django 4.1 on 2022-11-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email_institucional',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='nif',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'ALUMNO'), ('P', 'PROFESOR')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='titulacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
    ]
