# Generated by Django 4.1.3 on 2022-12-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reservas_usuario'),
        ('users', '0003_alter_user_titulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reservas',
            field=models.ManyToManyField(related_name='reservas_de_usuario', to='reservas.reservas'),
        ),
    ]
